<?php

namespace app\app\core\config;

use app\app\core\Router;

class Route extends Router
{
    public static function get($path, $handler)
    {
        parent::get($path, $handler); // TODO: Change the autogenerated stub
    }

    public static function post($path, $handler)
    {
        parent::post($path, $handler); // TODO: Change the autogenerated stub
    }

    public static function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
    }
}